apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  labels:
    app: example-app
  annotations:
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: aimvector/python:1.0.1
        imagePullPolicy: Always
        ports:

1

apiVersion: apps/v1

2

kind: Deployment

3

metadata:

4

  name: example-deploy

5

  labels:

6

    app: example-app

7

  annotations:

8

spec:

9

  selector:

10

    matchLabels:

11

      app: example-app

12

  replicas: 2

13

  strategy:

14

    type: RollingUpdate

15

    rollingUpdate:

16

      maxSurge: 1

17

      maxUnavailable: 0

18

  template:

19

    metadata:

20

      labels:

21

        app: example-app

22

    spec:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets/
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: secret-volume
        secret:
          secretName: mysecret
      - name: config-volume
        configMap:
          name: example-config #name of our configmap object
